// Code generated by goctl. DO NOT EDIT!

package postTag_db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postTagFieldNames          = builder.RawFieldNames(&PostTag{})
	postTagRows                = strings.Join(postTagFieldNames, ",")
	postTagRowsExpectAutoSet   = strings.Join(stringx.Remove(postTagFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	postTagRowsWithPlaceHolder = strings.Join(stringx.Remove(postTagFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"

	cacheIyuaPostTagIdPrefix = "cache:iyua:postTag:id:"
)

type (
	postTagModel interface {
		Insert(ctx context.Context, data *PostTag) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PostTag, error)
		Update(ctx context.Context, data *PostTag) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPostTagModel struct {
		sqlc.CachedConn
		table string
	}

	PostTag struct {
		Id     int64 `db:"id"`
		TagId  int64 `db:"tag_id"`
		PostId int64 `db:"post_id"`
	}
)

func newPostTagModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPostTagModel {
	return &defaultPostTagModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`post_tag`",
	}
}

func (m *defaultPostTagModel) Delete(ctx context.Context, id int64) error {
	iyuaPostTagIdKey := fmt.Sprintf("%s%v", cacheIyuaPostTagIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, iyuaPostTagIdKey)
	return err
}

func (m *defaultPostTagModel) FindOne(ctx context.Context, id int64) (*PostTag, error) {
	iyuaPostTagIdKey := fmt.Sprintf("%s%v", cacheIyuaPostTagIdPrefix, id)
	var resp PostTag
	err := m.QueryRowCtx(ctx, &resp, iyuaPostTagIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postTagRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostTagModel) Insert(ctx context.Context, data *PostTag) (sql.Result, error) {
	iyuaPostTagIdKey := fmt.Sprintf("%s%v", cacheIyuaPostTagIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, postTagRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TagId, data.PostId)
	}, iyuaPostTagIdKey)
	return ret, err
}

func (m *defaultPostTagModel) Update(ctx context.Context, data *PostTag) error {
	iyuaPostTagIdKey := fmt.Sprintf("%s%v", cacheIyuaPostTagIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postTagRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TagId, data.PostId, data.Id)
	}, iyuaPostTagIdKey)
	return err
}

func (m *defaultPostTagModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheIyuaPostTagIdPrefix, primary)
}

func (m *defaultPostTagModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postTagRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPostTagModel) tableName() string {
	return m.table
}
