// Code generated by goctl. DO NOT EDIT.
package types

type Tag struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type Post struct {
	Id          string `json:"id"`
	CreateAt    int64  `json:"createAt"`
	IsAnonymous bool   `json:"isAnonymous"`
	Title       string `json:"title"`
	Text        string `json:"text"`
	CoverUrl    string `json:"coverUrl"`
	Tags        []Tag  `json:"tags"`
	User_id     int64  `json:"userId"`
	Status      int64  `json:"status"`
	Is_delete   bool   `json:"isDelete"`
	DeleteAt    int64  `json:"deleteAt"`
}

type ListReq struct {
	Skip  int64 `json:"skip"`
	Count int64 `json:"count"`
}

type ListResp struct {
	Posts []Post `json:"posts"`
}

type RetrieveReq struct {
	PostId string `json:"postId"`
}

type RetrieveResp struct {
	Post_ Post `json:"post"`
}

type CreatReq struct {
	Post_ Post `json:"post"`
}

type CreatResp struct {
	PostId string `json:"postId"`
}

type UpdateReq struct {
	Post_ Post `json:"post"`
}

type UpdateResp struct {
}

type DestroyReq struct {
	PostId string `json:"postId"`
}

type DestroyResp struct {
}
