// Code generated by goctl. DO NOT EDIT.
// Source: post.proto

package postrpc

import (
	"context"

	"github.com/xh-polaris/meowchat-post-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePostReq        = pb.CreatePostReq
	CreatePostResp       = pb.CreatePostResp
	DeletePostReq        = pb.DeletePostReq
	DeletePostResp       = pb.DeletePostResp
	ListPostByUserIdReq  = pb.ListPostByUserIdReq
	ListPostByUserIdResp = pb.ListPostByUserIdResp
	ListPostReq          = pb.ListPostReq
	ListPostResp         = pb.ListPostResp
	Post                 = pb.Post
	RetrievePostReq      = pb.RetrievePostReq
	RetrievePostResp     = pb.RetrievePostResp
	SearchPostReq        = pb.SearchPostReq
	SearchPostResp       = pb.SearchPostResp
	UpdatePostReq        = pb.UpdatePostReq
	UpdatePostResp       = pb.UpdatePostResp

	PostRpc interface {
		SearchPost(ctx context.Context, in *SearchPostReq, opts ...grpc.CallOption) (*SearchPostResp, error)
		CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
		RetrievePost(ctx context.Context, in *RetrievePostReq, opts ...grpc.CallOption) (*RetrievePostResp, error)
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error)
		DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error)
		ListPost(ctx context.Context, in *ListPostReq, opts ...grpc.CallOption) (*ListPostResp, error)
		ListPostByUserId(ctx context.Context, in *ListPostByUserIdReq, opts ...grpc.CallOption) (*ListPostByUserIdResp, error)
	}

	defaultPostRpc struct {
		cli zrpc.Client
	}
)

func NewPostRpc(cli zrpc.Client) PostRpc {
	return &defaultPostRpc{
		cli: cli,
	}
}

func (m *defaultPostRpc) SearchPost(ctx context.Context, in *SearchPostReq, opts ...grpc.CallOption) (*SearchPostResp, error) {
	client := pb.NewPostRpcClient(m.cli.Conn())
	return client.SearchPost(ctx, in, opts...)
}

func (m *defaultPostRpc) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	client := pb.NewPostRpcClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultPostRpc) RetrievePost(ctx context.Context, in *RetrievePostReq, opts ...grpc.CallOption) (*RetrievePostResp, error) {
	client := pb.NewPostRpcClient(m.cli.Conn())
	return client.RetrievePost(ctx, in, opts...)
}

func (m *defaultPostRpc) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error) {
	client := pb.NewPostRpcClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultPostRpc) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error) {
	client := pb.NewPostRpcClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultPostRpc) ListPost(ctx context.Context, in *ListPostReq, opts ...grpc.CallOption) (*ListPostResp, error) {
	client := pb.NewPostRpcClient(m.cli.Conn())
	return client.ListPost(ctx, in, opts...)
}

func (m *defaultPostRpc) ListPostByUserId(ctx context.Context, in *ListPostByUserIdReq, opts ...grpc.CallOption) (*ListPostByUserIdResp, error) {
	client := pb.NewPostRpcClient(m.cli.Conn())
	return client.ListPostByUserId(ctx, in, opts...)
}
